### ISSUE TITLE
能否提供0.4.0集成版的源码呢?

### ISSUE THREAD

**Issue by Seventysecond** [ma459006574/kettle-manager#15]
能否提供0.4.0集成版的源码呢?  目前GITHUB上的源码跟集成版的程式有差异

能否提供源码呢?  谢谢

**Comment by SophieRoyal** [comment]
你好， 我不是原开发者，我这里也没有所有的文件，我只有所有的lib。有问题可以去我们群里面问744936894

在 2019-04-12 13:27:38，"YuTien" <notifications@github.com> 写道：


能否提供0.4.0集成版的源码呢? 目前GITHUB上的源码跟集成版的程式有差异

能否提供源码呢? 谢谢

**Comment by Seventysecond** [comment]
你好

好的   我已尝试加入群里

你手边的LIB能分享给我吗?

谢谢

Tony

**Comment by hxp0618** [comment]
> 能否提供0.4.0集成版的源码呢？目前的GitHub上的源码跟集成版的程式有差异
> 
> 能否提供源码呢？谢谢

请问你有0.4版本的源码吗

**Comment by SophieRoyal** [comment]
I'm not Ma Jinzhi. I don't have the source code here.

在 2019-07-23 10:01:19，"hxp0618" <notifications@github.com> 写道：


能否提供0.4.0集成版的源码呢？目前的GitHub上的源码跟集成版的程式有差异

能否提供源码呢？谢谢

请问你有0.4版本的源码吗

**Comment by majinju** [comment]
最新版本源码已更新
