### ISSUE TITLE
无法登录Web端

### ISSUE THREAD

**Issue by liCN** [ma459006574/kettle-manager#16]
你好，majinju
使用中出现以下错误
登录时跳转到 kettle/toLogin，页面显示为

![1](https://user-images.githubusercontent.com/3488352/60568425-60266280-9d9f-11e9-9b3d-27762ce8756e.jpg)
配置文件
![2](https://user-images.githubusercontent.com/3488352/60568480-8ba94d00-9d9f-11e9-8016-974142989dc1.jpg)
请问是哪里的配置出现问题？

原因已找到，只要nginx 转发设置了 IP白名单，就会报错，原因未知

server {
    listen 80;
    server_name kettle;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
#IP acl fail,unset
#        allow ;
#        deny all;
        proxy_pass http://10.0.0.1:82;
    }
}

**Comment by majinju** [comment]
请使用新版本
