### ISSUE TITLE
How can I integrate big-data-plugin into a web project?

### ISSUE THREAD

**Issue by REIGE** [ma459006574/kettle-manager#17]
Hello,

 

I want to integrate PDI into my web project, and now I can integrate the functionality under the kettle-engine package. But there is something wrong with integrating big-data-plugin.

 

Example:

I need a HBaseInput and HBaseOutput, so I initialized it like this:

```
KettleEnvironment.init();
PluginRegistry registry = PluginRegistry.getInstance();
PluginInterface pluginInterface= registry.findPluginWithId(StepPluginType.class, "HBaseInput");
HBaseInputMeta meta = (HBaseInputMeta)registry.loadClass(pluginInterface);
```
 

But the line 4 causes [ClassCastException]

 

I looked at the source and found that they are different classloaders.

 

So I don't know how to integrate this into my project now, I am not familiar with OSGI. : (

 

Could you help me ?

Many thanks in advance. : )

**Comment by SophieRoyal** [comment]
Hello brother:

I'm not majinju, nor do I develop kettle manager.

I'm an open-source user of majinju / kettle manager like you.

I can't answer your questions for the time being. Add these two QQ groups, '744936894' and '142104962', but fortunately,

I joined the QQ group of kettle manager. Some questions can be discussed and solved together.

Sophie·Royal







At 2019-10-30 16:40:41, "REIGE" <notifications@github.com> wrote:


Hello,

I want to integrate PDI into my web project, and now I can integrate the functionality under the kettle-engine package. But there is something wrong with integrating big-data-plugin.

Example:

I need a HBaseInput and HBaseOutput, so I initialized it like this:

KettleEnvironment.init();
PluginRegistry registry = PluginRegistry.getInstance();
PluginInterface pluginInterface= registry.findPluginWithId(StepPluginType.class, "HBaseInput");
HBaseInputMeta meta = (HBaseInputMeta)registry.loadClass(pluginInterface);


But the line 4 causes [ClassCastException]

I looked at the source and found that they are different classloaders.

So I don't know how to integrate this into my project now, I am not familiar with OSGI. : (

Could you help me ?

Many thanks in advance. : )

**Comment by majinju** [comment]
本系统默认没有集成kettle的额外插件库，如需要使用hive等大数据等插件，需要将data-integration-8.3中的plugins目录拷贝到解压目录中sjsj/hd目录下。
