### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by zhaoxuefei-ai** [ma459006574/kettle-manager#18]
`11:10:27.724 [main] DEBUG cn.hutool.log.LogFactory - Use [Slf4j] Logger As Default.
11:10:27.759 [main] DEBUG druid.sql.Connection - {conn-10001} connected
11:10:27.773 [main] DEBUG druid.sql.Connection - {conn-10002} connected
11:10:27.778 [main] INFO com.alibaba.druid.pool.DruidDataSource - {dataSource-1,default} inited
11:10:27.779 [main] DEBUG druid.sql.Connection - {conn-10002} pool-connect
11:10:27.780 [main] DEBUG druid.sql.Connection - {conn-10002} pool-recycle
11:10:27.801 [main] DEBUG druid.sql.Connection - {conn-10002} pool-connect
11:10:27.803 [main] DEBUG druid.sql.Statement - {conn-10002, pstmt-20000} created. SELECT
    t.TABLE_COMMENT comments
FROM
    information_schema.TABLES t
WHERE t.TABLE_SCHEMA=?
    and t.TABLE_NAME = ?
11:10:27.872 [main] DEBUG druid.sql.Statement - {conn-10002, pstmt-20000} Parameters : [kettle_default, r_jobentry]
11:10:27.872 [main] DEBUG druid.sql.Statement - {conn-10002, pstmt-20000} Types : [VARCHAR, VARCHAR]
11:10:27.931 [main] DEBUG druid.sql.Statement - {conn-10002, pstmt-20000} executed. select t.TABLE_COMMENT as comments
from information_schema.TABLES t
where t.TABLE_SCHEMA = 'kettle_default'
	and t.TABLE_NAME = 'r_jobentry'
11:10:27.931 [main] DEBUG druid.sql.Statement - {conn-10002, pstmt-20000, rs-50000} query executed. 59.437 millis. SELECT
    t.TABLE_COMMENT comments
FROM
    information_schema.TABLES t
WHERE t.TABLE_SCHEMA=?
    and t.TABLE_NAME = ?
11:10:27.931 [main] DEBUG druid.sql.ResultSet - {conn-10002, pstmt-20000, rs-50000} open
11:10:27.931 [main] DEBUG druid.sql.ResultSet - {conn-10002, pstmt-20000, rs-50000} Header: [TABLE_COMMENT]
11:10:27.932 [main] DEBUG druid.sql.ResultSet - {conn-10002, pstmt-20000, rs-50000} closed
11:10:27.932 [main] DEBUG druid.sql.Statement - {conn-10002, pstmt-20000} closed
11:10:27.932 [main] DEBUG druid.sql.Connection - {conn-10002} pool-recycle
11:10:27.932 [main] ERROR cn.benma666.iframe.BasicObject - r_jobentry找不到

Process finished with exit code 0`

**Comment by majinju** [comment]
就是大小写问题，小写不行就配置成大写，sql也看到了，拿sql去数据库跑，sql跑出数据程序就能找到表了
