### ISSUE TITLE
can not find dependency jar

### ISSUE THREAD

**Issue by zhaoweijing2003** [ma459006574/kettle-manager#4]
<dependency>
			<groupId>cn.benma666</groupId>
			<artifactId>myutils</artifactId>
			<version>0.0.1</version>
        </dependency>

**Comment by majinju** [comment]
可以从部署包中获取，运行源码之前先运行发布的部署包，部署包能运行起来，你需要的都能在里面找到。

**Comment by huangxl5** [comment]
您好，你说的部署包在哪里啊，上面那个依赖的jar包，没有呢，能否给我发一个呢？邮箱：342996111@qq.com

**Comment by 545314690** [comment]
我也是找不到这个包，怎么解决呢？

**Comment by DearAS** [comment]
请问你说的部署包是指哪个呢？myutils这个jar包应该如何获取 能把部署包链接发一下吗

**Comment by huangxl5** [comment]
在作者的一个博文里面：
https://www.cnblogs.com/majinju/p/5767001.html
认真阅读，有下载地址。工程解压出来，里面有myutils的包

**Comment by majinju** [comment]
上面答得好
