### ISSUE TITLE
0.2.0发行版中快速查询页面搜索结果无法显示部分列，但是导出数据会显示

### ISSUE THREAD

**Issue by Arcko** [ma459006574/kettle-manager#5]
![6 6w7t3 mv2b5t r16trb](https://user-images.githubusercontent.com/17232/30488113-05897efc-9a68-11e7-9eaf-986c1f2eb9f7.png)

这个ID无法显示，但是导出数据里有ID

![f ii _ zb3 vcls00 _ o](https://user-images.githubusercontent.com/17232/30488122-0b1a5238-9a68-11e7-9180-3f3d8ccf9636.png)
看起来是个前台的BUG？

**Comment by bigdatadl** [comment]
之前遇到过类似问题，在元数据定义时，将数据库对应的表名写成小写即可。这可能是因为json里都需要是小写的，否则对应不上。看下是否是因为这个原因。

**Comment by Arcko** [comment]
是这原因，谢谢楼上！
