### ISSUE TITLE
程序正常运行，但是登录成功后页面无内容

### ISSUE THREAD

**Issue by jamescheng16** [ma459006574/kettle-manager#8]
按照0.2.0配置，启动一切正常。
登录成功后页面只有

> 关闭
> 
> 关闭其他
> 
> 关闭所有
> 

这几个文本信息

 控制台输出如下

`
Sql: select * from eova_menu where parent_id = 0 order by order_num

Sql: select DISTINCT(b.menu_code) from eova_role_btn rf LEFT JOIN eova_button b on rf.bid = b.id where b.ui = 'query' and rf.rid = ?

Sql: select * from eova_menu where is_del = 0 order by parent_id,order_num

Sql: select DISTINCT(b.menu_code) from eova_role_btn rf LEFT JOIN eova_button b on rf.bid = b.id where b.ui = 'query' and rf.rid = ?

Sql: select DISTINCT(b.menu_code) from eova_role_btn rf LEFT JOIN eova_button b on rf.bid = b.id where b.ui = 'query' and rf.rid = ?

JFinal action report -------- 2018-01-29 14:29:31 ------------------------------

Controller  : com.eova.core.IndexController.(IndexController.java:1)

Method      : index

Interceptor : com.eova.interceptor.LoginInterceptor.(LoginInterceptor.java:1)

------------------------------------------------------------------------------
`

**Comment by majinju** [comment]
应该是配置文件中domain_static参数的问题，你可以看谷歌浏览器的控制台报错

**Comment by jamescheng16** [comment]
@majinju  按照您说的修改 domain_static 解决问题了， 感觉现在部署还是有点不方便， 有没有考虑过 docker 的方式部署？

**Comment by majinju** [comment]
请使用新版本
