### ISSUE TITLE
IDEA 导入项目的时候，pom文件提示缺少依赖包

### ISSUE THREAD

**Issue by GreyZeng** [ma459006574/kettle-manager#9]
<dependency>
			<groupId>cn.benma666</groupId>
			<artifactId>myutils</artifactId>
			<version>0.0.1</version>
        </dependency>

这个依赖包无法下载，要到哪里去获取这个依赖包呢？

**Comment by kuruizhixin** [comment]
同样的问题 困扰了很久

**Comment by majinju** [comment]
请使用新版本，所有依赖已上传maven中央仓库
